# Site settings
title: Bon Salu
header-img: img/home-bg.jpg
email: karin@bonsalu.nl
description: "Orthomoleculair Natuurvoedings Deskundige"
baseurl: ""
url: "http://bonsalu.nl"
twitter_username:
github_username:
facebook_username:
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
